before_script:
    - date
    - uname -a
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - make versions	
    - printenv | sort

cs331e-idb:
    image: "python:3.7"
    script:
    - ls -al
#    - make test
