# This file specifies your Python application's runtime configuration.
# See https://cloud.google.com/appengine/docs/managed-vms/config for details.

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

##[START env]
#env_variables:
#    # postgresql+psycopg2://USER:PASSWORD@/DATABASE?host=/cloudsql/INSTANCE_CONNECTION_NAME
#    # Replace user, password, database, and instance connection name with the values obtained
#    # when configuring your Cloud SQL instance.
#    # postgresql+psycopg2://postgres:asd123@/postgres?host=/cloudsql/cs331e-idb:us-central1:bookdb
#    DB_STRING: >-
#      postgresql://zuvviiky:gUj52EfnqxD2UeVkSPQ7kDeiAQOwMcu6@queenie.db.elephantsql.com:5432/zuvviiky
##[END env]
#
##[START cloudsql_settings]
## Replace project and instance with the values obtained  when configuring your
## Cloud SQL instance.
#beta_settings:
#    cloud_sql_instances: cs331e-idb:us-central1:bookdb

# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
#[END cloudsql_settings]

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  # this is not doing anything which is okay :) please do not change it thanks
  - url: /statics
    static_dir: statics

    # This handler routes all requests not caught above to your main app. It is
    # required when static routes are defined, but can be omitted (along with
    # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto
